image: Visual Studio 2019
version: 1.0.{build}
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true

before_build:
- cmd: nuget restore

after_build:
- cmd: nuget pack BuildTools\SocketRx.nuspec

build:
  publish_nuget: true
  verbosity: minimal

artifacts:
- path: '**\SocketRx.*.nupkg'

deploy:
- provider: NuGet

  api_key:
    secure: CIdiwHmj8amXRtjE0AwwlBSj55TGDg0yLqm/YthICWaUncKoJmYabpu2YqXIuOVd
