<Project DefaultTargets="Build"
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Authors>Chris Pulman</Authors>
    <Description>An Observable Socket extension of System.Net.Sockets.Socket</Description>
    <Copyright>Copyright © https://github.com/ChrisPulman $([System.DateTime]::Now.ToString(yyyy))</Copyright>
    <IsTestProject>$(MSBuildProjectName.Contains('Tests'))</IsTestProject>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
    <Configuration>$(TargetFramework)</Configuration>
    <Company>ChrisPulman</Company>
    <NoWarn>CS1591</NoWarn>
    <Nullable>enable</Nullable>
    <PackageReleaseNotes>Added compatability with Net 8 / 9</PackageReleaseNotes>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/ChrisPulman/SocketRx</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ChrisPulman/SocketRx</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!--https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/-->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <!-- Include PDB in the built .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)images\logo.png" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="LICENSE" />
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <!--<Compile Update="**\*.cs" DependentUpon="I%(Filename).cs" />-->
    <PackageReference Include="stylecop.analyzers" Version="1.2.0-beta.435" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.13.1" PrivateAssets="All" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>
